services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    env_file:
      - .env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=unifi-flows
      - DOCKER_INFLUXDB_INIT_BUCKET=network-data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource

  # If you want to run the unifi-flows app in a container too (optional)
  # NOTE: Playwright might need additional dependencies depending on your OS
  unifi-flows:
    build: .
    container_name: unifi-flows
    restart: always
    depends_on:
      - influxdb
    volumes:
      - ./downloads:/app/downloads
      - ./data:/app/data
      - ./geoip:/app/geoip
      - ./.env:/app/.env
    env_file:
      - .env
    environment:
      - USE_INFLUXDB=true
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-super-secret-auth-token
      - INFLUXDB_ORG=unifi-flows
      - INFLUXDB_BUCKET=network-data
      - GEOIP_ENABLED=true
      - API_PORT=3001
      - USE_BUN=true # Ensure Bun is used for execution
      # These settings will override the .env file values
      # Uncomment if you want to set them here instead
      # - DIRECT_IMPORT=true
      # - UNIFI_USERNAME=admin
      # - UNIFI_PASSWORD=password
      # - UNIFI_URL=https://10.5.22.112
    command: ["bun", "src/index.js"] # Explicitly use Bun to run the app

volumes:
  influxdb-data:
  influxdb-config:
  grafana-storage:
